/*
 *  This file was generated by xsltproc from the matching .xml file.
 *  Additions and changes should be made to the original .xml.
 *  Please see the matching .xml for copyright and license.
 */

static fbInfoElement_t infomodel_array_static_cert[] = {
    FB_IE_INIT_FULL("templateName", 6871, 1000, FB_IE_VARLEN, FB_IE_DEFAULT, 0, 0, FB_STRING, NULL),
    FB_IE_INIT_FULL("templateDescription", 6871, 1001, FB_IE_VARLEN, FB_IE_DEFAULT, 0, 0, FB_STRING, NULL),

    FB_IE_NULL
};
